<a href="https://colab.research.google.com/github/nrkfeller/YCBS_258_Winter_2019/blob/master/Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Basics
* Tensords and Basic Operations
* Numpy interoperability
* Type Conversions
* Variables

In [1]:
# Choose Python 3 runtime
!pip install --upgrade tensorflow

     |████████████████████████████████| 86.3MB 40kB/s 
     |████████████████████████████████| 3.8MB 46.8MB/s 
  Using cached https://files.pythonhosted.org/packages/fc/08/8b927337b7019c374719145d1dceba21a8bb909b93b1ad6f8fb7d22c1ca1/tensorflow_estimator-2.0.1-py2.py3-none-any.whl
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


In [3]:
import tensorflow as tf
tf.__version__

'2.0.0'

### Tensors and Operations

In [4]:
# matrix
tf.constant([[1., 2., 3.], [4., 5., 6.]])

<tf.Tensor: id=0, shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [5]:
# scalar
tf.constant(42)

<tf.Tensor: id=1, shape=(), dtype=int32, numpy=42>

In [6]:
t = tf.constant([[1.,2.,3.], [4.,5.,6.,]])
t.shape

TensorShape([2, 3])

In [7]:
t.dtype

tf.float32

In [8]:
t[:, 1:]

<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [9]:
t[..., 1, tf.newaxis]

<tf.Tensor: id=10, shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [10]:
# basic arithmetic
print("Addition: t + 10", t + 10)
print("Square t^2:", tf.square(t))
print("Transpose of t:", tf.transpose(t))

Addition: t + 10 tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
Square t^2: tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
Transpose of t: tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)


In [0]:
?tf.add()

### Keras' Low Level API
Keras's "backend" typically used as "K" can call the corresponding tensorflow functions. (most common ones but not all)

In [12]:
from tensorflow import keras

K = keras.backend
K.square(K.transpose(t)) + 10

<tf.Tensor: id=20, shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

### Tensorflow and Numpy
You can easily move from tensorflow to Numpy

Note that tensorflow uses 32 bit precison rather than the standard 64 bit preceision used in numpy. This is because neural networks need less precision - sometimes way less, but this is a topic for a different time

In [0]:
import numpy as np

In [14]:
a = np.array([2.,4., 5.])
tf.constant(a)

<tf.Tensor: id=21, shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [15]:
t.numpy() # same as np.array(t)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [16]:
tf.square(a)

<tf.Tensor: id=23, shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [17]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

### Type Conversions
No implicit type conversions - you must cast. This removes lots of potentially dramatic issues

In [18]:
tf.constant(2.) + tf.constant(40)
tf.constant(2.) + tf.constant(40., dtype=tf.float64)

InvalidArgumentError: ignored

In [19]:
t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: id=29, shape=(), dtype=float32, numpy=42.0>

### Variables
Constants are, well ... contant. Weights and Biases need to be variables.

In [20]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [21]:
v.assign(2 * v)           # => [[2., 4., 6.], [8., 10., 12.]]
v[0, 1].assign(42)        # => [[2., 42., 6.], [8., 10., 12.]]
v[:, 2].assign([0., 1.])  # => [[2., 42., 0.], [8., 10., 1.]]
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>

In [22]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>